# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3
exclude: |
  (?x)(
    migrations/|
    .idea/|
    venv/|
    .git/
  )
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=900"]
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.90.13
    hooks:
      - id: trufflehog

  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-fmt
      - id: go-mod-tidy-repo
      - id: go-vet-repo-mod
      - id: go-sec-repo-mod
      - id: go-staticcheck-mod
      - id: go-lint

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
      - id: actionlint
